<form action="index.php" method="post" id="formLogin">
    <p id="pLogin">Inicia Sesión</p>
    <br><br>
    <input type='text' id="name" name='name' required placeholder="Nombre usuario" />
    <br><br>
    <input type='password' id="password" name='password' required placeholder="Contraseña" />
    <br><br><br>
    <div>
        <button type="submit" name="controller" value="login">Inicia sesión</button>
        <button type="button" onclick="window.location.href='index.php';">Volver</button>
    </div>
</form>
