<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKzQ1rdO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKzQ1rdO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKzQ1rdO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKzQ1rdO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKzQ1rdO\App_KernelDevDebugContainer([
    'container.build_hash' => 'KzQ1rdO',
    'container.build_id' => '5b253192',
    'container.build_time' => 1736707217,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKzQ1rdO');
