<form method="post" action="index.php" enctype="multipart/form-data">

    <!--  PRODUCTO -->
    <input type="text" name="name" placeholder="Nombre de producto" value="<?php echo $productUpd->getName() ?>">
    <input type="file" name="img" accept="image/*" placeholder="Elegir imagen" value="<?php echo $productUpd->getImg() ?>">
    <input type="text" name="description" placeholder="Descripción del producto" value="<?php echo $productUpd->getDescription() ?>">
    <input type="number" name="price" step="0.01" min="0" placeholder="Precio" value="<?php echo $productUpd->getPrice() ?>" />
    <input type="number" name="stock" step="1" min="0" placeholder="Cantidad" value="<?php echo $productUpd->getStock() ?>" />

    <!-- VARIABLES FIJAS -->
    <input type="hidden" name="controller" value="crudProducts">
    <input type="hidden" name="state" value="upd">
    <button type="submit" name="crudP" value="create">Modificar</button>

</form>
<br> <br>
<button type="button" onclick="window.location.href='index.php';">Volver</button>
