<style>
  * {
    margin: 0;
  }

  body {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    height: 100vh;
  }


  /* CABECERA LANDING */

  #divLanding {
    width: 100%;
    height: 70px;
    margin-bottom: 20px;
    display: flex;
    text-align: center;
    justify-content: center;
    align-items: center;
  }

  #titleLanding {
    width: 100%;
    color: black;
    font-size: 50px;
  }


  #divFormLanding {
    width: 350px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }

  #divFormLanding p {
    font-size: 30px;
  }

  #formLanding {

    width: 250px;
    height: 70px;
    display: flex;
    justify-content: space-evenly;
    align-items: center;
  }

  #formLanding button {
    width: 100px;
    height: 40px;
    font-weight: bold;
    border-radius: 10px;
    border-color: grey;
  }

  button:hover {
    background-color: black;
    color: white;
    border-color: none;
  }


  /* FORMULARIO LOGIN */
  #formLogin {
    width: 250px;
    text-align: center;
    border: 1px solid #ccc;
    padding: 40px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }

  #formLogin input {
    border-radius: 5px;
    width: 200px;
    height: 20px;
  }

  #pLogin {
    font-size: 25px;
    font-weight: 800;
  }

  #formLogin div {
    display: flex;
    flex-direction: row;
    justify-content: space-evenly;
    width: 100%;
  }

  #formLogin button {
    width: 100px;
    height: 30px;
    font-weight: bold;
    border-radius: 10px;
    border-color: grey;
  }

  /* FORMULARIO REGISTER */

  #formRegister {
    width: 250px;
    text-align: center;
    border: 1px solid #ccc;
    padding: 40px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }

  #formRegister input {
    border-radius: 5px;
    width: 200px;
    height: 20px;
  }

  #pRegister {
    font-size: 25px;
    font-weight: 800;
  }

  #formRegister div {
    display: flex;
    flex-direction: row;
    justify-content: space-evenly;
    width: 100%;
  }

  #formRegister button {
    width: 100px;
    height: 30px;
    font-weight: bold;
    border-radius: 10px;
    border-color: grey;
  }

  /* CABECERA ADMINISTRADOR */
  #headerAdmin {
    background-color: lightgrey;
    width: 100%;
    height: 100px;
    display: flex;
    justify-content: space-between;
    position: fixed; 
    top: 0; 
    left: 0; 
    z-index: 1000;
}

  /* CABECERA CLIENTE */
  #headerUser {
    background-color: lightgrey;
    width: 100%;
    height: 100px;
    display: flex;
    justify-content: space-between;
    position: fixed; 
    top: 0; 
    left: 0; 
    z-index: 1000;
}



/* DETALLE PRODUCTO */
#productDetailContainer {
    width: 80%;
    max-width: 500px;
    margin-top: 120px;
    padding: 20px;
    border: 1px solid #ddd;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    background-color: #fafafa;
    text-align: center;
    font-family: Arial, sans-serif;
}

#productDetailContainer h2 {
    font-size: 26px;
    font-weight: bold;
    color: #333;
    margin-bottom: 15px;
}


/* DETALLE USUARIO */
#userDetailContainer{
  width: 80%;
    max-width: 500px;
    margin-top: 120px;
    padding: 20px;
    border: 1px solid #ddd;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    background-color: #fafafa;
    text-align: center;
    font-family: Arial, sans-serif;
}


/* CREAR PRODUCTO */
#productFormContainer{
   width: 80%;
   max-width: 400px;
   margin-top: 50px;
   padding: 20px;
   border: 1px solid #ddd;
   border-radius: 10px;
}

</style>