<h2>Tu perfil</h2>
<img src="<?php echo $user_session->getAvatar(); ?>" alt="Avatar" style="border-radius: 50%; width: 100px; height: 100px;">
<p>Email: <?php echo $user_session->getEmail(); ?></p>
<p>Biografía: <?php echo $user_session->getBio() ?: 'Sin contenido'; ?></p>
<p>Estado: <?php echo $user_session->state() ? 'Activo' : 'Inactivo'; ?></p>
<form method="post" action="index.php">
    <input type='hidden' name='controller' value='user'>
    <input type='hidden' name='action' value='edit'>
    <input type='hidden' name='id' value=' <?php $user_session->getId() ?> '>
    <button type="submit" id="btn-editProfile">Editar perfil</button>
</form>