<form method="post" action="index.php">
    <h3>Datos para la transferencia bancaria:</h3>
    <p>Realiza la transferencia al siguiente número de cuenta:</p>
    <p><strong>Número de cuenta:</strong> 1234-5678-9101-1121</p>
    <p><strong>Banco:</strong> CaixaBank</p>
    <p><strong>Beneficiario:</strong>TOB</p>
    <input type="text" id="ref_transferencia" name="ref_transferencia" required placeholder="Número de referencia">

    <button type="submit" name="confirmar_pago_transferencia">Confirmar Pago</button>
</form>