<form action="index.php" method="post" id="formRegister">
    <p id="pRegister">Registrate</p>
    <br><br>
    <input type='text' id='username' name='username' required placeholder="Nombre usuario" />
    <br><br>
    <input type='email' id="email" name='email' required placeholder="Email" />
    <br><br>
    <input type='password' id="password" name='password' required placeholder="Contraseña" />
    <br><br>
    <input type='password' id="password2" name='password2' required placeholder="Repite la contraseña" />
    <br><br><br>
    <div>
        <button type="submit" name="controller" value="register">Registrar</button>
        <button type="button" onclick="window.location.href='index.php';">Volver</button>
    </div>
</form>