<div id="headerAdmin">
    <h1>cabecera del index ADMIN</h1>
    <form method="post" action="index.php">
        <button type="submit" name="controller" value="crudOrders">Gestionar pedidos</button>
        <button type="submit" name="controller" value="crudProducts">Gestionar productos</button>
        <button type="submit" name="controller" value="crudUsers">Gestionar usuarios</button>
        <button type="button" onclick="window.location.href='index.php';">Inicio</button>
    </form>
</div>