<div id="divLanding">
    <h1 id="titleLanding">Bienvenido a la Tienda Online Básica</h1>
</div>

<div id="divFormLanding">
    <?php
      if (!isset($_SESSION['user'])) { ?> 
    <p>¿Tienes una cuenta creada?</p>
    <?php
      }
    ?>
    <form method="post" action="index.php" id="formLanding">
        <?php
        if (!isset($_SESSION['user'])) { ?>
            <button type="submit" name="controller" value="login">Inicia sesión</button>
            <button type="submit" name="controller" value="register">Regístrate</button>
        <?php
        } else {
            if (isset($_SESSION['user'])) {
                echo "<h3>Hola " . $_SESSION['user'] . "<br></h3>";
            }
        ?>
            <button type="submit" name="controller" value="logout">Cerrar sesión</button>
            <button type="submit" name="controller" value="index">Entrar</button>
        <?php
        }
        ?>
    </form>
</div>
